language: go

go:
  - 1.15
before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get honnef.co/go/tools/cmd/staticcheck
script:
  - $HOME/gopath/bin/staticcheck ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
